### ISSUE TITLE
Migrate code generator .proto -> .ts from protobufjs to Telescope

### ISSUE THREAD

**Issue by webmaster128** [cosmos/ics23#219]
In https://github.com/cosmos/ics23/pull/217 it was brought up the that current TypeScript code generator is not working properly anymore. My suggestion is to replace it instead of try to fix it.

There are basically 3 generations of TypeScript code generation we (Confio) used over the years

1. protobufjs (pretty old school, TS types are generated out of JavaScript doc comments)
2. ts-proto (quite nice, but a bit slow as it is a protoc plugin and does not allow interpreting Cosmos specific options)
3. Telescope (most advanced solution)

It would be great to get the the TypeScript code generation migrated from 1. (used now) to 3. In addition to being the most powerful and convenient solution, it also means we can remove protobufjs runtime dependency, which is often reported as having security issues.

This affects the code in the `generated` folder, not the rest: https://github.com/cosmos/ics23/tree/master/js/src/generated. The generated types will be organized slightly differently but it should not be hard to adapt the JS codebase to it.

**Comment by crodriguezvega** [comment]
I will close the issue, since [we removed the Typescript implementation](https://github.com/cosmos/ics23/pull/353).
