### ISSUE TITLE
`EmptyBranchTestData` as json

### ISSUE THREAD

**Issue by benluelo** [cosmos/ics23#265]
It would be nice if the [`EmptyBranchTestData`](https://github.com/cosmos/ics23/blob/master/go/proof_data_test.go#L99-L187) was in json format, so it could be reused by other implementations.

**Comment by crodriguezvega** [comment]
@benluelo I opened #269 to change this, please let me know if it works for you.

**Comment by benluelo** [comment]
yes, looks great! thank you!
