### ISSUE TITLE
Store proofs.proto in schema registry

### ISSUE THREAD

**Issue by alpe** [cosmos/ics23#67]
Store the protobuf definition in the [buf schema registry](https://docs.buf.build/tour/add-a-dependency) so that it can be retrieved easily by other projects. 

Ref :https://github.com/cosmos/cosmos-sdk/pull/10669

**Comment by ethanfrey** [comment]
This seems related to https://github.com/confio/ics23/pull/59

I have little knowledge of buf but happy to merge if someone knows how to set this up for all 3 supported languages

**Comment by colin-axner** [comment]
Closing this issue as I believe this is now occurring: https://buf.build/cosmos/ics23 (please reopen if I am mistaken)
