### ISSUE TITLE
Key comparison in proof generated from SMT

### ISSUE THREAD

**Issue by yito88** [cosmos/ics23#83]
I'm wondering if the hashed key in proof generated from SMT can be compared in ibc-go's verification.
https://github.com/confio/ics23/blob/8ea0b239740068dd004fe4a42a1d861cd607611c/go/ics23.go#L138

In ibc-go, the proof is verified with the corresponding non-hashed key. However, the proof generated from SMT has only the hashed key. The verification would fail due to the key mismatching.

- Set the hashed key to an existence proof generated from SMT
https://github.com/cosmos/cosmos-sdk/blob/1ebe76c4801022c688613012f75f5406cc53e83d/store/tools/ics23/smt/create.go#L54

- Verify an existence proof in ibc-go
https://github.com/cosmos/ibc-go/blob/e59a6d2b88fbd543016b0a148b19fac368696ad9/modules/core/23-commitment/types/merkle.go#L247

Is that just because ibc-go has not supported SMT's proof yet?
I guess that ibc-go cannot avoid this issue because a chain trying to verify a proof doesn't know if the key in the proof is hashed or not.

**Comment by ethanfrey** [comment]
@AdityaSripal or other core ibc-go team, I would love your feedback here and in #88 

You would know the problem and implications best. I would be fine reviewing the pr and merging if you say that is the best approach, but I don't have context to judge the architecture

**Comment by AdityaSripal** [comment]
responded here: https://github.com/confio/ics23/pull/88#issuecomment-1191306720

**Comment by crodriguezvega** [comment]
Is this issue still relevant after #136 was merged?

**Comment by AdityaSripal** [comment]
Closed by #136
